[[task]]
    id = "dev"
    type = "long"
    dependencies = ["backend", "client"]
    env = { APP_ENV = "DEV", CLICOLOR_FORCE = "1" }
    cmd = """
        echo "Starting the dev server..."
        echo "APP_ENV: $APP_ENV"
    """

[[task]]
    id = "backend"
    type = "short"
    dependencies = ["zipkin"]
    env = { CLICOLOR_FORCE = "1" }
    cmd = """
        echo "Running the backend..."
        cd server
        npm install
        npx ts-node src/server.ts
    """

[[task]]
    id = "client"
    type = "short"
    dependencies = ["zipkin"]
    env = { PORT = "3001", CLICOLOR_FORCE = "1" }
    cmd = """
        echo "Running the client..."
        cd client
        npm install
        npm start
    """

# These are for reference, usually the docker compose file is used instead
[[task]]
    id = "zipkin"
    type = "short"
    cmd = "docker compose up -d zipkin"

[[task]]
    id = "stop-zipkin"
    type = "short"
    cmd = "docker compose down zipkin"
