[[task]]
  id = "dev"
  type = "long"
  environment = { CLICOLOR_FORCE = "1" }
  cmd = """
    echo "Starting development server..."
    go run ./cmd/server/main.go
  """

###
[[task]]
  id = "run-bin"
  type = "short"
  dependencies = ["build"]
  cmd = "./bin/smail"

[[task]]
  id = "build"
  type = "short"
  cmd = "go build -o ./bin/smail ./cmd/app/main.go"

[[task]]
  id = "test"
  type = "short"
  cmd = "go test -v ./..."
###

[[task]]
  id = "gqlgen"
  type = "short"
  cmd = """
    go get github.com/99designs/gqlgen@v0.17.55
    go run github.com/99designs/gqlgen generate
  """
