################################################################################
# Production tasks
#
# FOR REFERENCE ONLY
################################################################################
[[task]]
    id = "build"
    description = """
    - Build the production version of the server.
    - Compiled code is written to the gitignored `dist` directory.
    """
    type = "short"
    cmd = "npx tsc"

[[task]]
    id = "serve"
    description = """
    - Run the production version of the server.
    - The server listens on port `3000`.
    """
    type = "short"
    dependencies = ["build"]
    cmd = "node dist/server.js"